domain: hellundschön.de
lang: en
color: "#13ccf9"
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
title: "hell & schön"
author: J. R. Schmid
email: jrs+git@weitnahbei.de
description: >- # this means to ignore newlines until "baseurl:"
  Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. Blah, blah blah blah, blah. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sixtyfive
plugins:
  - jekyll-feed
  - jekyll-seo-tag
